### ISSUE TITLE
English documentation request.

### ISSUE THREAD

**Issue by huntzhan** [hayajo/macbook-provision#2]

**Comment by soulmachine** [comment]
# Macbook Development Environment Provision

## Preparation

### Install Xcode Command Line Tools

Before installing Xcode Command Lint Tools, we neeed to agree its license.

    sudo xcodebuild -license
    xcode-select --install

### Install Homebrew

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew doctor
    brew update

### Install Python

    brew install python
    pip install --upgrade pip setuptools
    brew linkapps python

Add python to the `PATH` environment variable, for example, for zsh add the following lines to `~/.zprofile`:

    PATH=/usr/local/bin:$PATH
    export PATH

### Install Ansible

    sudo pip install ansible

## Apply the playbook to install everything

    ansible-playbook -i localhost, -vv playbook.yml

## Update

    ansible-playbook -i localhost, -vv playbook.yml

## ghq

    export GOPATH=$HOME
    export PATH=$GOPATH/bin:$PATH
    go get github.com/motemen/ghq

## VirtualBox, Vagrant, Chrome

* [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
* [Vagrant](https://www.vagrantup.com/downloads.html)
* [Chrome](https://www.google.co.jp/chrome/browser/desktop/index.html)

**Comment by soulmachine** [comment]
@hayajo I don't know much about Japanese, but I can guess most of them, the English Document above is far from precise, so you can go ahead and modify it.

**Comment by hayajo** [comment]
@soulmachine  Thank you very much!
